## YAML Template.
---
version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn package
    - mv target/ROOT.WAR ROOT.WAR
  post_build:
    commands:
    - echo "Entered the post-build phase"
    artifacts:
      files:
        - ROOT.WAR
